### ISSUE TITLE
El campo "Tematica" de la tabla "Revista" no está normalizado.

### ISSUE THREAD

**Issue by gerAlvarez** [Programacion-Web-II/eMagazine#1]
Hay que hacer una tabla TEMATICA y relacionarla con la tabla REVISTA.

`REVISTA -n---<>---1- TEMATICA`

**Las modificaciones hay que hacerlas en el DER y en el script de creación de la db.**

**Comment by Juanmanuel245** [comment]
Es necesario hacer esto?? Ya que TEMATICA es decorativa, no la usamos para nada

**Comment by gerAlvarez** [comment]
No creo, pero si lo borras o alguien lo borra actualicen el DER.

2016-06-22 15:47 GMT-03:00 Juan Manuel <notifications@github.com>:

> Es necesario hacer esto?? Ya que TEMATICA es decorativa, no la usamos para
> nada
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Programacion-Web-II/eMagazine/issues/1#issuecomment-227840384>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANBVJ8zSRvDSRWLR-TVVKqEco3XPfhrgks5qOYM2gaJpZM4IkJ-X>
> .
>



-- 
Atentamente, Alvarez Germán Rodrigo.

**Comment by Juanmanuel245** [comment]
Fue eliminada de la base de datos
