### ISSUE TITLE
La base de datos esta sin versionar.

### ISSUE THREAD

**Issue by gerAlvarez** [Programacion-Web-II/eMagazine#2]
Hay que crear la tabla de versión en la db para llevar un control de la versión de la misma.

**Comment by Juanmanuel245** [comment]
Esto que era?

**Comment by gerAlvarez** [comment]
Algo que a estas alturas no tiene sentido hacer. Cerralo y listo.

2016-06-22 15:46 GMT-03:00 Juan Manuel <notifications@github.com>:

> Esto que era?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Programacion-Web-II/eMagazine/issues/2#issuecomment-227840186>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANBVJ3sN7t_PrsFEwbQkBBSWhS2z1Iwyks5qOYMMgaJpZM4Ila13>
> .
>



-- 
Atentamente, Alvarez Germán Rodrigo.

**Comment by Briankuz** [comment]
Se agrego nuevos pattern para nombres

pattern="[A-zA-Z0-9./\s/][a-zA-ZÑÁÉÍÓÚáéíóú./\s/][a-zA-Zñáéíóú./\s/]{3,15}"

funciona de manera exitosa

2016-06-22 21:59 GMT-03:00 Juan Manuel <notifications@github.com>:
