### ISSUE TITLE
cardProducto.php | Deberia traer solo las ediciones publicadas

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#20]
Ahora estra trayendo todas las ediciones, deberia fijarse si la edicion tiene el estado de publicada o si es borrador...y de serlo, ignorarla

**Comment by gerAlvarez** [comment]
¿Tenemos en la base de datos ediciones sin publicar? Capaz te trae todo porque todo esta publicado.

**Comment by Juanmanuel245** [comment]
@gerAlvarez  Tenemos todas las ediciones publicadas, pero el algoritmo de busqueda no discrimina por estado de publicacion

**Comment by gerAlvarez** [comment]
Ah!, ok. El problema es que no esta escrito como corresponde el algoritmo. Listo ! ya entendí.
