### ISSUE TITLE
La entidad Edicion carece de un atributo que nos permita identificar su estado

### ISSUE THREAD

**Issue by gerAlvarez** [Programacion-Web-II/eMagazine#21]
> create table if not exists EDICION (
> ID_EDICION int primary key auto_increment not null,
> ID_REVISTA int not null, -- FK
> ID_USUARIO int not null, -- FK
> FECHA_PUBLICACION datetime,
> TAPA varchar (80),
> PRECIO decimal(5,2) not null, -- Esto significa un numero de hasta cinco digitos de los cuales dos son decimales.
> PRECIO_POR_SUSCRIPCION decimal(5,2),
> **ID_ESTADO_REVISTA int not null, -- FK**
> FECHA_MODIFICACION datetime,
> DESCRIPCION varchar (400) -- UNIQUE
> );

¿Para qué nos sirve el estado de la revista?

De la forma que esta actualmente no podemos saber si la Edición esta actualmente publicada o en borrador, por lo tanto no podemos realizar una consulta efectiva que nos traiga las ediciones publicadas.

Si el atributo **ID_ESTADO_REVISTA** fuera en su lugar **ID_ESTADO_EDICION** (o algo similar) con la siguiente consulta podriamos traer solo las ediciones publicadas:

```
SELECT *
FROM EDICION
WHERE ID_ESTADO_EDICION = 1 /* Donde 1 significa que esta publicada*/
```

**Comment by Juanmanuel245** [comment]
La tabla que marca el ESTADO tanto de Revista como de Edicion y Nota es la tabla ESTADO_REVISTA, la cual esta mal nombrada, hay que cambiarle el nombre por uno mas generico

**Comment by gerAlvarez** [comment]
Ponele Estado_Contenido o alguno que te guste. Sino consulta en el grupo a
ver que opina el resto.

El 28 de junio de 2016, 16:51, Juan Manuel <notifications@github.com>
escribió:

> La tabla que marca el ESTADO tanto de Revista como de Edicion y Nota es la
> tabla ESTADO_REVISTA, la cual esta mal nombrada, hay que cambiarle el
> nombre por uno mas generico
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Programacion-Web-II/eMagazine/issues/21#issuecomment-229162417>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANBVJzVfoD0WMX9Gtw7i4RYPBXT0MwK8ks5qQXtRgaJpZM4JAc-B>
> .
>



-- 
Atentamente, Alvarez Germán Rodrigo.

**Comment by Juanmanuel245** [comment]
Solucionado...

Se reemplazo ESTADO_REVISTA por ESTADO_CONTENIDO asi se puede utilizar en todos lados sin prestar confusion
