### ISSUE TITLE
Convertir Documentos a PDF

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#28]
Se requiere poder descargar las ediciones en formato PDF

**Comment by Juanmanuel245** [comment]
Le deje la pregunta en el foro al profesor, a ver si nos puede comentar como era la forma de vincularlo

**Comment by Briankuz** [comment]
Juan,mañana lo veo lo del pdf,no te hagas drama

**Comment by Juanmanuel245** [comment]
Ya los transforma bien, ahora hay que ver el tema que no acepta imagenes remotas externas...si el profe no responde las hago locales y lo soluciono
