### ISSUE TITLE
No deberian poder editar o borrar notas publicadas

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#31]
Habria que poner una restriccion

**Comment by gerAlvarez** [comment]
¿Los contenedistas actualmente pueden hacer eso? Pensé que esto lo habías hecho o te faltó cerrarlo?

**Comment by Juanmanuel245** [comment]
No! eso no lo habia hecho, pero detecte el bug n.n ahora estoy por hacerlo
