### ISSUE TITLE
Los acentos y Ñ no son tomados correctamente de la Base de Datos

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#4]
Cuando tratas de traer informacion de la BD que contiene caracteres especiales te los trae con simbolos extraños

**Comment by gerAlvarez** [comment]
¿Esto no lo habías resuelto?

**Comment by Juanmanuel245** [comment]
Modificando a mano el sql, pero deberia existir otra manera...que pasa si un usuario ingresa un apellido con Ñ en el campo ?


Una manera de resolverlo podria ser aplicar la funcion que cambia simbolos extraños por los accute, y pasarla en cada campo de entrada, pero tiene que haber una mejor

**Comment by gerAlvarez** [comment]
¿Por qué usar la función no te parece una buena forma?

**Comment by Juanmanuel245** [comment]
Porque tiene que existir otra manera que sea mas general, no que tengas que forzar los campos

**Comment by gerAlvarez** [comment]
¿A qué te referís con forzar los campos? El valor de los campos (y sus acentos) no van a cambiar, lo que haces es tomar el valor del campo, convertir una copia y meter esa copia en el html, eso es lo que hace la función, convertir una copia del campo no el campo en si mismo.

**Comment by gerAlvarez** [comment]
¿En qué quedó este bug?

**Comment by Juanmanuel245** [comment]
El script sql que almacena datos en la DB esta puesto con acentos, y la Base de Datos los almacena correctamente, pero cuando lo muestra en el sitio no se ven bien... debe faltar algun UTF

**Comment by gerAlvarez** [comment]
Estamos guardando HTML en la descripción de la edición (no sé que tan malo sea esto).

**Comment by Juanmanuel245** [comment]
Lo cierro, ya nos dijo facu que no le demos bola a esto por que ellos no le van a dar bola
