### ISSUE TITLE
Pais, Provincia, Localidad

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#5]
Hay que hacer que por medio de la ID muestre las provincias de ese pais y las localidades de ese pais

**Comment by gerAlvarez** [comment]
¿Esto no lo habías resuelto?

**Comment by Juanmanuel245** [comment]
No!, tengo que encontrar la manera que al seleccionar el pais le pase el dato del ID_PAIS a Provincia, posiblemente usando ajax

**Comment by gerAlvarez** [comment]
"Posiblemente" no, hay que usar Ajax ! no se tiene que recargar la pagina y eso solo se hace con Ajax.

**Comment by Juanmanuel245** [comment]
Bueno si, hoy intento mirarlo!

**Comment by gerAlvarez** [comment]
Aclaro que no te estoy diciendo que lo hagas hoy o que lo hagas, eso es algo que puedo hacer yo también. Lo que quise resaltar es que no vamos a zafar de usar Ajax.

**Comment by Juanmanuel245** [comment]
Listo! Armado con ajax :)!
