### ISSUE TITLE
No guarda correctamente fechas en la Base de Datos

### ISSUE THREAD

**Issue by Juanmanuel245** [Programacion-Web-II/eMagazine#6]
A la hora de cargar las fechas dentro de la base de datos la carga vacia
![captura](https://cloud.githubusercontent.com/assets/7252246/15629715/cb296c0a-24f6-11e6-8619-fb223be5bd87.PNG)

**Comment by gerAlvarez** [comment]
¿En qué archivo y número de línea estas armando el query que inserta la fecha en la db?.

**Comment by Juanmanuel245** [comment]
En el archivo registro.php LINEA 41
