### ISSUE TITLE
Al completar los campos en la pagina de registracion, falla en Apellido y Nombre de usuario

### ISSUE THREAD

**Issue by Briankuz** [Programacion-Web-II/eMagazine#7]
Al querer registrar rompe en apeliido y nombre de usuario
Se hicieron pruebas al respecto 
-Se sacaron validaciones del Front y del back para ver si ese era el error.
finalmente se pudo ver que no es tema de validacion del front o del back
![Uploading reg.PNG…]()

- Al dar este error, nos deberia dar un mensaje de error en la registracion, pero nos esta mostrando un mensaje de OK

-El insert no se esta impactando en la BD

**Comment by Juanmanuel245** [comment]
SOLUCIONADO: HAbian borrado los atributos "name=" de los tags correspondientes
